#
# Releaser workflow setup
# https://goreleaser.com/ci/actions/
#
name: release

# run only on tags
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access
  attestations: write # needed for attestations publishing

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # this is important, otherwise it won't checkout the full tree (i.e. no previous tags)
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true
      - uses: sigstore/cosign-installer@v3.7.0         # installs cosign
      - uses: anchore/sbom-action/download-syft@v0.17.9 # installs syft
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: docker/login-action@v3                   # login to ghcr
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v6          # run goreleaser
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Export digest
        id: digest
        run: |
          echo digest=$(docker buildx imagetools inspect ghcr.io/belphemur/adguard-exporter:latest --format "{{json .Manifest.Digest}}"  | xargs) >> $GITHUB_OUTPUT
      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ghcr.io/belphemur/adguard-exporter
          subject-digest: ${{ steps.digest.outputs.digest }}
          push-to-registry: true
